  hosts: all
  name: "Transfer and execute a script."
  tasks: 
    - 
      file: "path=/tmp/test1.txt state=touch"
      name: touch
    - 
      file: "path=/tmp/test1.txt mode=777"
      name: file
    - 
      copy: "src=/tmp/test1.txt dest=/tmp/test2.txt remote_src=yes"
      name: copy
    - 
      name: copy11
      shell: "/tmp/test.sh >> somelog.txt"
